### ISSUE TITLE
Improvement request - create an issue and delete the offending branch after a grace period.

### ISSUE THREAD

**Issue by chaos-generator** [greggigon/brunchyyy#2]
Hi Greg,

Can I suggest that brunchyyy initially creates and issue in the project and if the issue (and the offending branch) are not handled within X amount of time, then the offending branch is deleted?

This grace period allows offenders to right their ways before the whip cracks....

Kind regards,
chaos-generator

**Comment by greggigon** [comment]
Hi Augusto

Not a bad idea.

At the moment, Brunchyyy will not delete branches at all, unless the `deleteBranch: true` is placed in the `.github/brunchyyy.yml` file. So the Robot only goes ballistic if you tell it to :) 

Otherwise, it just raises issues.
